language: go
go: 1.x
os:
  - linux
before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/alecthomas/gometalinter
install:
  - $GOPATH/bin/dep ensure
  - $GOPATH/bin/gometalinter --install
